version: "3"
networks:
  command-bot-network:

services:
  dev:
    build: .
    deploy:
    restart: unless-stopped
    volumes:
      - "./:/command.bot"
      - "/command.bot/.vs"
      - "/command.bot/src/Command.Bot/bin"
      - "/command.bot/src/Command.Bot.Core/bin"
      - "/command.bot/src/Command.Bot.Core.Tests/bin"
      - "/command.bot/src/Command.Bot.Service/bin"
      - "/command.bot/src/Command.Bot.Shared/bin"
      - "/command.bot/src/Command.Bot/obj"
      - "/command.bot/src/Command.Bot.Core/obj"
      - "/command.bot/src/Command.Bot.Core.Tests/obj"
      - "/command.bot/src/Command.Bot.Service/obj"
      - "/command.bot/src/Command.Bot.Shared/obj"
    networks:
      - command-bot-network
