name: .NET

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Test
        run: make test
      - name: Create artifacts
        run: make publish-zip
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-service-zip
          path: |
            dist/*.zip
      - name: Create and publish nuget
        env:
          NUGET_KEY: ${{secrets.NUGET_KEY}}
        run: make publish-nuget
      - name: docker publish
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          make publish
