name: .NET

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x
      - name: Test
        run: make test
      - name: Test
        run: make test
      - name: Create artifacts
        run: make publish-zip
      - name: Create and publish nuget
        run: make publish-nuget
      - name: docker publish
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          make publish
